version: '2'
services:
  # Notice how the service name, container name and repo directory (where the Dockerfile lives) all match.
  flask-skeleton-api:
    container_name: flask-skeleton-api
    build: /vagrant/apps/flask-skeleton-api
    ports:
      # Dockerfiles should always expose 8080 by default, we map it here ot a unique port for the app
      # which is subsequently used to expose outside of vagrant too
      - "9999:8080"
    volumes:
      # Our convention is (for python) to always map the app files to /src within the container
      - /vagrant/apps/flask-skeleton-api:/src
