"""empty message

Revision ID: 35977fdf6c77
Revises: 
Create Date: 2019-10-25 13:14:00.803406

"""
from alembic import op
from flask import current_app
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35977fdf6c77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ba_unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spatial_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_paid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spatial_unit_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spatial_unit_id'], ['spatial_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsibility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ba_unit_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ba_unit_id'], ['ba_unit.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restriction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('ba_unit_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ba_unit_id'], ['ba_unit.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('right',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('ba_unit_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ba_unit_id'], ['ba_unit.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spatial_unit_ba_unit_association',
    sa.Column('spatial_unit_id', sa.Integer(), nullable=False),
    sa.Column('ba_unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ba_unit_id'], ['ba_unit.id'], ),
    sa.ForeignKeyConstraint(['spatial_unit_id'], ['spatial_unit.id'], ),
    sa.PrimaryKeyConstraint('spatial_unit_id', 'ba_unit_id')
    )
    op.create_table('mortgage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restriction_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['restriction_id'], ['restriction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mortgage_right_association',
    sa.Column('mortgage_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mortgage_id'], ['mortgage.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['right.id'], ),
    sa.PrimaryKeyConstraint('mortgage_id', 'right_id')
    )
    # ### end Alembic commands ###

    op.execute("GRANT SELECT, INSERT ON TABLE \"spatial_unit\", \"ba_unit\", \"party\",  \"responsibility\", \
               \"right\", \"restriction\", \"price_paid\", \"mortgage\", \"spatial_unit_ba_unit_association\", \
               \"mortgage_right_association\" TO " + current_app.config.get("APP_SQL_USERNAME"))
    op.execute("GRANT USAGE ON SEQUENCE \"ba_unit_id_seq\", \"right_id_seq\", \"responsibility_id_seq\", \
               \"restriction_id_seq\", \"party_id_seq\", \"price_paid_id_seq\" TO " + current_app.config.get('APP_SQL_USERNAME'))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mortgage_right_association')
    op.drop_table('mortgage')
    op.drop_table('spatial_unit_ba_unit_association')
    op.drop_table('right')
    op.drop_table('restriction')
    op.drop_table('responsibility')
    op.drop_table('price_paid')
    op.drop_table('spatial_unit')
    op.drop_table('party')
    op.drop_table('ba_unit')
    # ### end Alembic commands ###
