"""Initial database structure

Revision ID: 6d90af1169bd
Revises: 
Create Date: 2019-10-02 12:57:57.995714

"""
from alembic import op
from flask import current_app
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d90af1169bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('ba_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spatial_unit_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ba_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ba_unit_id'], ['ba_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('responsibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['interest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('restriction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('party_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['interest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('right',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['interest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('mortgage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['restriction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("GRANT SELECT, INSERT ON ba_unit TO " + current_app.config.get("APP_SQL_USERNAME"))
    op.execute("GRANT SELECT, INSERT ON party TO " + current_app.config.get("APP_SQL_USERNAME"))
    op.execute("GRANT SELECT, INSERT ON interest TO " + current_app.config.get("APP_SQL_USERNAME"))
    op.execute("GRANT SELECT, INSERT ON responsibility TO " + current_app.config.get("APP_SQL_USERNAME"))
    op.execute("GRANT SELECT, INSERT ON restriction TO " + current_app.config.get("APP_SQL_USERNAME"))
    op.execute('GRANT SELECT, INSERT ON "right" TO ' + current_app.config.get("APP_SQL_USERNAME"))
    op.execute("GRANT SELECT, INSERT ON mortgage TO " + current_app.config.get("APP_SQL_USERNAME"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mortgage')
    op.drop_table('right')
    op.drop_table('restriction')
    op.drop_table('responsibility')
    op.drop_table('interest')
    op.drop_table('party')
    op.drop_table('ba_unit')
    # ### end Alembic commands ###
